import defaultMdxComponents from 'fumadocs-ui/mdx';
import type { MDXComponents } from 'mdx/types';
import { Card, Cards } from 'fumadocs-ui/components/card';
import { Callout } from 'fumadocs-ui/components/callout';
import { Tab, Tabs } from 'fumadocs-ui/components/tabs';
import { Step, Steps } from 'fumadocs-ui/components/steps';
import { File, Files, Folder } from 'fumadocs-ui/components/files';
import {
  AccordionPreview,
  AlertPreview,
  AlertDialogPreview,
  AspectRatioPreview,
  AvatarPreview,
  BadgePreview,
  BreadcrumbPreview,
  ButtonPreview,
  ButtonGroupPreview,
  CalendarPreview,
  CardPreview,
  CarouselPreview,
  ChartPreview,
  CheckboxPreview,
  CollapsiblePreview,
  ColorsPreview,
  ComboboxPreview,
  CommandPreview,
  ContextMenuPreview,
  DialogPreview,
  DrawerPreview,
  DropdownMenuPreview,
  EmptyPreview,
  FieldPreview,
  HoverCardPreview,
  InputPreview,
  InputGroupPreview,
  InputOTPPreview,
  ItemPreview,
  KbdPreview,
  LabelPreview,
  MenuPreview,
  MenubarPreview,
  NativeSelectPreview,
  NavigationMenuPreview,
  PaginationPreview,
  PopoverPreview,
  ProgressPreview,
  RadioGroupPreview,
  ResizablePreview,
  ScrollAreaPreview,
  SelectPreview,
  SeparatorPreview,
  SheetPreview,
  SkeletonPreview,
  SliderPreview,
  SonnerPreview,
  SpinnerPreview,
  SwitchPreview,
  TablePreview,
  TabsPreview,
  TextareaPreview,
  TogglePreview,
  ToggleGroupPreview,
  TooltipPreview,
} from '@/components/previews';

export function getMDXComponents(components?: MDXComponents) {
  return {
    ...defaultMdxComponents,
    Card,
    Cards,
    Callout,
    Tab,
    Tabs,
    Step,
    Steps,
    File,
    Files,
    Folder,
    AccordionPreview,
    AlertPreview,
    AlertDialogPreview,
    AspectRatioPreview,
    AvatarPreview,
    BadgePreview,
    BreadcrumbPreview,
    ButtonPreview,
    ButtonGroupPreview,
    CalendarPreview,
    CardPreview,
    CarouselPreview,
    ChartPreview,
    CheckboxPreview,
    CollapsiblePreview,
    ColorsPreview,
    ComboboxPreview,
    CommandPreview,
    ContextMenuPreview,
    DialogPreview,
    DrawerPreview,
    DropdownMenuPreview,
    EmptyPreview,
    FieldPreview,
    HoverCardPreview,
    InputPreview,
    InputGroupPreview,
    InputOTPPreview,
    ItemPreview,
    KbdPreview,
    LabelPreview,
    MenuPreview,
    MenubarPreview,
    NativeSelectPreview,
    NavigationMenuPreview,
    PaginationPreview,
    PopoverPreview,
    ProgressPreview,
    RadioGroupPreview,
    ResizablePreview,
    ScrollAreaPreview,
    SelectPreview,
    SeparatorPreview,
    SheetPreview,
    SkeletonPreview,
    SliderPreview,
    SonnerPreview,
    SpinnerPreview,
    SwitchPreview,
    TablePreview,
    TabsPreview,
    TextareaPreview,
    TogglePreview,
    ToggleGroupPreview,
    TooltipPreview,
    ...components,
  } satisfies MDXComponents;
}

export const useMDXComponents = getMDXComponents;

declare global {
  type MDXProvidedComponents = ReturnType<typeof getMDXComponents>;
}
